export const metadata = {
  title: 'Muhammed Ramadan',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      
        {children}
       
      </body>
    </html>
  )
}
